apiVersion: v1
kind: Service
metadata:
  name: wildfly-service
  namespace: wildfly
spec:
  type: NodePort
  selector:
    app: wildfly-ap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    # - protocol: TCP
    #   port: 9990
    #   targetPort: 9990
