on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test-deploy:
    name: Build and deploy container image to test namespace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Google Cloud
        id: gcp_auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA }}
      - name: Login to Google Cloud Aritfact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_HOST }}
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.access_token }}
      - name: Setup Docker Buildx (Buildkit)
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_NAME }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
      - name: Configure kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GCP_GKE_CLUSTER }}
          location: ${{ secrets.GCP_GKE_LOCATION }}
      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: Deploy to test namespace
        shell: bash
        run: |
          pushd kustomize/overlay/test
          ./kustomize edit set namespace ${{ secrets.K8S_TEST_NS }}
          ./kustomize edit set image wildfly-image=${{ vars.CONTAINER_REGISTRY_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_NAME }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
          ./kustomize build . | kubectl apply -f -
